# Generated by Django 5.0.1 on 2024-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalytic',
            name='avg_reading_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='useranalytic',
            name='max_reading_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='useranalytic',
            name='min_reading_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='useranalytic',
            name='total_reading_time_30_days',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='useranalytic',
            name='total_reading_time_7_days',
            field=models.DurationField(null=True),
        ),
    ]
